# The Nameless GPU
#
# Copyright (C) 2013 Jacob Holt & Matthew Brades.
# All rights reserved.
# This code is licensed under the NGPUL, file ngpul.txt,
# which you should have recieved with this code.
# If not, please email Jacob Holt at jacob.matthew.holt<at>gmail.com

TEST_ITEMS = hdmi.v

test: $(TEST_ITEMS)

*.v:
	iverilog -t null $<
